name: Bug report
description: Report a bug in bun-ready
title: "[bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide a minimal reproduction if possible.
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: bun version, OS, repo type (monorepo/single), lockfile
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / report output
      description: Paste the relevant output (redact secrets).
    validations:
      required: false
